"use strict";

module.exports = {
  allSets: [
    { code: "fdn", count: 730, name: "Foundations", price: 5 },
    { code: "j25", count: 779, name: "Foundations Jumpstart", price: 5 },
    { code: "dsk", count: 417, name: "Duskmourn: House of Horror", price: 26 },
    { code: "blb", count: 397, name: "Bloomburrow", price: 29 },
    { code: "acr", count: 309, name: "Assassin's Creed", price: 6 },
    { code: "mh3", count: 527, name: "Modern Horizons 3", price: 45 },
    { code: "otj", count: 374, name: "Outlaws of Thunder Junction", price: 25 },
    { code: "pip", count: 1068, name: "Fallout", price: 5 },
    { code: "clu", count: 284, name: "Ravnica: Clue Edition", price: 20 },
    { code: "mkm", count: 450, name: "Murders at Karlov Manor", price: 25 },
    { code: "rvr", count: 531, name: "Ravnica Remastered", price: 34 },
    { code: "lci", count: 416, name: "The Lost Caverns of Ixalan", price: 28 },
    { code: "who", count: 1178, name: "Doctor Who", price: 15 },
    { code: "wot", count: 103, name: "Wilds of Eldraine: Enchanting Tales", price: 5 },
    { code: "woe", count: 381, name: "Wilds of Eldraine", price: 28 },
    { code: "cmm", count: 1067, name: "Commander Masters", price: 50 },
    {
      code: "ltr",
      count: 856,
      name: "The Lord of the Rings: Tales of Middle-earth",
      price: 5
    },
    {
      code: "mat",
      count: 230,
      name: "March of the Machine: The Aftermath",
      price: 21
    },
    { code: "mom", count: 387, name: "March of the Machine", price: 25 },
    { code: "mul", count: 261, name: "Multiverse Legends", price: 5 },
    { code: "sir", count: 294, name: "Shadows over Innistrad Remastered", price: 5 },
    { code: "one", count: 479, name: "Phyrexia: All Will Be One", price: 31 },
    { code: "dmr", count: 457, name: "Dominaria Remastered", price: 25 },
    { code: "j22", count: 835, name: "Jumpstart 2022", price: 5 },
    { code: "30a", count: 594, name: "30th Anniversary Edition", price: 10 },
    { code: "bro", count: 399, name: "The Brothers' War", price: 25 },
    { code: "gn3", count: 135, name: "Game Night: Free-for-All", price: 1 },
    { code: "unf", count: 639, name: "Unfinity", price: 25 },
    { code: "dmu", count: 453, name: "Dominaria United", price: 23 },
    { code: "2x2", count: 579, name: "Double Masters 2022", price: 20 },
    { code: "hbg", count: 436, name: "Alchemy Horizons: Baldur's Gate", price: 10 },
    {
      code: "clb",
      count: 936,
      name: "Commander Legends: Battle for Baldur's Gate",
      price: 26
    },
    { code: "snc", count: 513, name: "Streets of New Capenna", price: 25 },
    { code: "neo", count: 531, name: "Kamigawa: Neon Dynasty", price: 27 },
    { code: "dbl", count: 535, name: "Innistrad: Double Feature", price: 5 },
    { code: "vow", count: 423, name: "Innistrad: Crimson Vow", price: 22 },
    { code: "mid", count: 400, name: "Innistrad: Midnight Hunt", price: 9 },
    { code: "j21", count: 389, name: "Jumpstart: Historic Horizons", price: 10 },
    {
      code: "afr",
      count: 424,
      name: "Adventures in the Forgotten Realms",
      price: 12
    },
    { code: "mh2", count: 494, name: "Modern Horizons 2", price: 26 },
    { code: "sta", count: 126, name: "Strixhaven Mystical Archive", price: 5 },
    { code: "stx", count: 393, name: "Strixhaven: School of Mages", price: 20 },
    { code: "tsr", count: 411, name: "Time Spiral Remastered", price: 10 },
    { code: "khm", count: 426, name: "Kaldheim", price: 25 },
    { code: "cmr", count: 718, name: "Commander Legends", price: 44 },
    { code: "klr", count: 302, name: "Kaladesh Remastered", price: 5 },
    { code: "plst", count: 4809, name: "The List", price: 5 },
    { code: "znr", count: 408, name: "Zendikar Rising", price: 26 },
    { code: "akr", count: 339, name: "Amonkhet Remastered", price: 5 },
    { code: "2xm", count: 384, name: "Double Masters", price: 32 },
    { code: "jmp", count: 497, name: "Jumpstart", price: 5 },
    { code: "m21", count: 397, name: "Core Set 2021", price: 26 },
    { code: "iko", count: 390, name: "Ikoria: Lair of Behemoths", price: 29 },
    { code: "thb", count: 358, name: "Theros Beyond Death", price: 25 },
    { code: "sld", count: 1681, name: "Secret Lair Drop", price: 99 },
    { code: "eld", count: 399, name: "Throne of Eldraine", price: 30 },
    { code: "m20", count: 345, name: "Core Set 2020", price: 7 },
    { code: "mh1", count: 255, name: "Modern Horizons", price: 10 },
    { code: "war", count: 312, name: "War of the Spark", price: 10 },
    { code: "rna", count: 273, name: "Ravnica Allegiance", price: 5 },
    { code: "uma", count: 254, name: "Ultimate Masters", price: 22 },
    { code: "grn", count: 273, name: "Guilds of Ravnica", price: 5 },
    { code: "m19", count: 314, name: "Core Set 2019", price: 7 },
    { code: "bbd", count: 256, name: "Battlebond", price: 10 },
    { code: "dom", count: 280, name: "Dominaria", price: 6 },
    { code: "a25", count: 249, name: "Masters 25", price: 7 },
    { code: "rix", count: 205, name: "Rivals of Ixalan", price: 9 },
    { code: "ust", count: 268, name: "Unstable", price: 6 },
    { code: "ima", count: 249, name: "Iconic Masters", price: 15 },
    { code: "xln", count: 289, name: "Ixalan", price: 9 },
    { code: "hou", count: 209, name: "Hour of Devastation", price: 7 },
    { code: "akh", count: 287, name: "Amonkhet", price: 10 },
    { code: "mm3", count: 249, name: "Modern Masters 2017", price: 20 },
    { code: "aer", count: 197, name: "Aether Revolt", price: 6 },
    { code: "pz2", count: 282, name: "Treasure Chest", price: 5 },
    { code: "kld", count: 278, name: "Kaladesh", price: 15 },
    { code: "cn2", count: 222, name: "Conspiracy: Take the Crown", price: 10 },
    { code: "emn", count: 208, name: "Eldritch Moon", price: 8 },
    { code: "ema", count: 249, name: "Eternal Masters", price: 28 },
    { code: "soi", count: 302, name: "Shadows over Innistrad", price: 6 },
    { code: "ogw", count: 187, name: "Oath of the Gatewatch", price: 6 },
    { code: "bfz", count: 299, name: "Battle for Zendikar", price: 7 },
    { code: "ori", count: 288, name: "Magic Origins", price: 6 },
    { code: "mm2", count: 249, name: "Modern Masters 2015", price: 18 },
    { code: "tpr", count: 269, name: "Tempest Remastered", price: 4 },
    { code: "dtk", count: 264, name: "Dragons of Tarkir", price: 9 },
    { code: "frf", count: 191, name: "Fate Reforged", price: 7 },
    { code: "ktk", count: 293, name: "Khans of Tarkir", price: 8 },
    { code: "m15", count: 284, name: "Magic 2015", price: 5 },
    { code: "vma", count: 325, name: "Vintage Masters", price: 5 },
    { code: "cns", count: 210, name: "Conspiracy", price: 5 },
    { code: "jou", count: 165, name: "Journey into Nyx", price: 6 },
    { code: "bng", count: 165, name: "Born of the Gods", price: 6 },
    { code: "ths", count: 249, name: "Theros", price: 6 },
    { code: "m14", count: 249, name: "Magic 2014", price: 5 },
    { code: "mma", count: 229, name: "Modern Masters", price: 30 },
    { code: "dgm", count: 156, name: "Dragon's Maze", price: 5 },
    { code: "gtc", count: 249, name: "Gatecrash", price: 6 },
    { code: "rtr", count: 274, name: "Return to Ravnica", price: 6 },
    { code: "m13", count: 249, name: "Magic 2013", price: 5 },
    { code: "pc2", count: 156, name: "Planechase 2012", price: 5 },
    { code: "avr", count: 244, name: "Avacyn Restored", price: 17 },
    { code: "dka", count: 158, name: "Dark Ascension", price: 8 },
    { code: "isd", count: 264, name: "Innistrad", price: 18 },
    { code: "m12", count: 249, name: "Magic 2012", price: 5 },
    { code: "nph", count: 175, name: "New Phyrexia", price: 34 },
    { code: "mbs", count: 155, name: "Mirrodin Besieged", price: 19 },
    { code: "me4", count: 269, name: "Masters Edition IV", price: 5 },
    { code: "ps11", count: 224, name: "Salvat 2011", price: 5 },
    { code: "td0", count: 197, name: "Magic Online Theme Decks", price: 5 },
    { code: "som", count: 249, name: "Scars of Mirrodin", price: 23 },
    { code: "m11", count: 249, name: "Magic 2011", price: 5 },
    { code: "dpa", count: 113, name: "Duels of the Planeswalkers", price: 5 },
    { code: "roe", count: 248, name: "Rise of the Eldrazi", price: 50 },
    { code: "wwk", count: 145, name: "Worldwake", price: 41 },
    { code: "zen", count: 269, name: "Zendikar", price: 46 },
    { code: "me3", count: 230, name: "Masters Edition III", price: 5 },
    { code: "hop", count: 169, name: "Planechase", price: 5 },
    { code: "m10", count: 249, name: "Magic 2010", price: 5 },
    { code: "arb", count: 145, name: "Alara Reborn", price: 23 },
    { code: "con", count: 145, name: "Conflux", price: 22 },
    { code: "ala", count: 250, name: "Shards of Alara", price: 26 },
    { code: "me2", count: 245, name: "Masters Edition II", price: 5 },
    { code: "eve", count: 180, name: "Eventide", price: 32 },
    { code: "shm", count: 302, name: "Shadowmoor", price: 50 },
    { code: "mor", count: 150, name: "Morningtide", price: 26 },
    { code: "lrw", count: 301, name: "Lorwyn", price: 54 },
    { code: "me1", count: 195, name: "Masters Edition", price: 5 },
    { code: "10e", count: 510, name: "Tenth Edition", price: 5 },
    { code: "fut", count: 180, name: "Future Sight", price: 48 },
    { code: "plc", count: 165, name: "Planar Chaos", price: 29 },
    { code: "tsp", count: 301, name: "Time Spiral", price: 29 },
    { code: "csp", count: 155, name: "Coldsnap", price: 27 },
    { code: "dis", count: 180, name: "Dissension", price: 27 },
    { code: "gpt", count: 167, name: "Guildpact", price: 25 },
    { code: "rav", count: 306, name: "Ravnica: City of Guilds", price: 5 },
    { code: "psal", count: 720, name: "Salvat 2005", price: 5 },
    { code: "9ed", count: 709, name: "Ninth Edition", price: 5 },
    { code: "sok", count: 165, name: "Saviors of Kamigawa", price: 25 },
    { code: "bok", count: 165, name: "Betrayers of Kamigawa", price: 36 },
    { code: "unh", count: 168, name: "Unhinged", price: 17 },
    { code: "chk", count: 307, name: "Champions of Kamigawa", price: 45 },
    { code: "5dn", count: 165, name: "Fifth Dawn", price: 28 },
    { code: "dst", count: 165, name: "Darksteel", price: 36 },
    { code: "mrd", count: 306, name: "Mirrodin", price: 40 },
    { code: "8ed", count: 710, name: "Eighth Edition", price: 5 },
    { code: "scg", count: 143, name: "Scourge", price: 26 },
    { code: "lgn", count: 145, name: "Legions", price: 33 },
    { code: "ons", count: 351, name: "Onslaught", price: 71 },
    { code: "jud", count: 143, name: "Judgment", price: 30 },
    { code: "tor", count: 143, name: "Torment", price: 38 },
    { code: "ody", count: 353, name: "Odyssey", price: 55 },
    { code: "apc", count: 143, name: "Apocalypse", price: 40 },
    { code: "7ed", count: 708, name: "Seventh Edition", price: 5 },
    { code: "pls", count: 146, name: "Planeshift", price: 53 },
    { code: "inv", count: 353, name: "Invasion", price: 45 },
    { code: "pcy", count: 144, name: "Prophecy", price: 28 },
    { code: "nem", count: 143, name: "Nemesis", price: 23 },
    { code: "mmq", count: 350, name: "Mercadian Masques", price: 108 },
    { code: "uds", count: 143, name: "Urza's Destiny", price: 267 },
    { code: "ptk", count: 180, name: "Portal Three Kingdoms", price: 1000 },
    { code: "6ed", count: 351, name: "Classic Sixth Edition", price: 77 },
    { code: "ulg", count: 143, name: "Urza's Legacy", price: 266 },
    { code: "usg", count: 356, name: "Urza's Saga", price: 345 },
    { code: "p02", count: 165, name: "Portal Second Age", price: 113 },
    { code: "exo", count: 143, name: "Exodus", price: 110 },
    { code: "sth", count: 143, name: "Stronghold", price: 167 },
    { code: "tmp", count: 350, name: "Tempest", price: 119 },
    { code: "wth", count: 167, name: "Weatherlight", price: 68 },
    { code: "por", count: 257, name: "Portal", price: 100 },
    { code: "5ed", count: 460, name: "Fifth Edition", price: 57 },
    { code: "vis", count: 167, name: "Visions", price: 72 },
    { code: "mir", count: 353, name: "Mirage", price: 109 },
    { code: "all", count: 199, name: "Alliances", price: 80 },
    { code: "ptc", count: 308, name: "Pro Tour Collector Set", price: 5 },
    { code: "hml", count: 140, name: "Homelands", price: 18 },
    { code: "ren", count: 122, name: "Renaissance", price: 5 },
    { code: "chr", count: 125, name: "Chronicles", price: 30 },
    { code: "ice", count: 383, name: "Ice Age", price: 36 },
    { code: "4ed", count: 379, name: "Fourth Edition", price: 43 },
    { code: "fem", count: 187, name: "Fallen Empires", price: 18 },
    { code: "drk", count: 122, name: "The Dark", price: 403 },
    { code: "sum", count: 306, name: "Summer Magic / Edgar", price: 5 },
    { code: "leg", count: 310, name: "Legends", price: 1167 },
    { code: "3ed", count: 306, name: "Revised Edition", price: 400 },
    { code: "atq", count: 102, name: "Antiquities", price: 5 },
    { code: "cei", count: 302, name: "Intl. Collectors' Edition", price: 5 },
    { code: "ced", count: 302, name: "Collectors' Edition", price: 5 },
    { code: "2ed", count: 302, name: "Unlimited Edition", price: 4000 },
    { code: "leb", count: 302, name: "Limited Edition Beta", price: 8000 },
    { code: "lea", count: 295, name: "Limited Edition Alpha", price: 10000 }
  ]
};
