"use strict";

module.exports = {
  allSets: [
    { code: "fdn", count: 730, name: "Foundations" },
    { code: "j25", count: 779, name: "Foundations Jumpstart" },
    { code: "dsc", count: 373, name: "Duskmourn: House of Horror Commander" },
    { code: "pdsk", count: 160, name: "Duskmourn: House of Horror Promos" },
    { code: "dsk", count: 417, name: "Duskmourn: House of Horror" },
    { code: "pblb", count: 160, name: "Bloomburrow Promos" },
    { code: "blb", count: 397, name: "Bloomburrow" },
    { code: "mb2", count: 385, name: "Mystery Booster 2" },
    { code: "blc", count: 356, name: "Bloomburrow Commander" },
    { code: "acr", count: 309, name: "Assassin's Creed" },
    { code: "m3c", count: 398, name: "Modern Horizons 3 Commander" },
    { code: "mh3", count: 527, name: "Modern Horizons 3" },
    { code: "potj", count: 160, name: "Outlaws of Thunder Junction Promos" },
    { code: "otc", count: 342, name: "Outlaws of Thunder Junction Commander" },
    { code: "otj", count: 374, name: "Outlaws of Thunder Junction" },
    { code: "pip", count: 1068, name: "Fallout" },
    { code: "clu", count: 284, name: "Ravnica: Clue Edition" },
    { code: "pmkm", count: 180, name: "Murders at Karlov Manor Promos" },
    { code: "mkc", count: 358, name: "Murders at Karlov Manor Commander" },
    { code: "mkm", count: 450, name: "Murders at Karlov Manor" },
    { code: "rvr", count: 531, name: "Ravnica Remastered" },
    { code: "plci", count: 154, name: "The Lost Caverns of Ixalan Promos" },
    { code: "lci", count: 416, name: "The Lost Caverns of Ixalan" },
    { code: "lcc", count: 370, name: "The Lost Caverns of Ixalan Commander" },
    { code: "who", count: 1178, name: "Doctor Who" },
    { code: "pwoe", count: 160, name: "Wilds of Eldraine Promos" },
    { code: "wot", count: 103, name: "Wilds of Eldraine: Enchanting Tales" },
    { code: "woc", count: 173, name: "Wilds of Eldraine Commander" },
    { code: "woe", count: 381, name: "Wilds of Eldraine" },
    { code: "cmm", count: 1067, name: "Commander Masters" },
    { code: "ltc", count: 591, name: "Tales of Middle-earth Commander" },
    {
      code: "ltr",
      count: 856,
      name: "The Lord of the Rings: Tales of Middle-earth",
    },
    { code: "mat", count: 230, name: "March of the Machine: The Aftermath" },
    { code: "moc", count: 450, name: "March of the Machine Commander" },
    { code: "mom", count: 387, name: "March of the Machine" },
    { code: "pmom", count: 134, name: "March of the Machine Promos" },
    { code: "mul", count: 261, name: "Multiverse Legends" },
    { code: "sir", count: 294, name: "Shadows over Innistrad Remastered" },
    { code: "da1", count: 368, name: "Unknown Event" },
    { code: "pone", count: 160, name: "Phyrexia: All Will Be One Promos" },
    { code: "one", count: 479, name: "Phyrexia: All Will Be One" },
    { code: "onc", count: 174, name: "Phyrexia: All Will Be One Commander" },
    { code: "dmr", count: 457, name: "Dominaria Remastered" },
    { code: "scd", count: 352, name: "Starter Commander Decks" },
    { code: "j22", count: 835, name: "Jumpstart 2022" },
    { code: "30a", count: 594, name: "30th Anniversary Edition" },
    { code: "brc", count: 209, name: "The Brothers' War Commander" },
    { code: "brr", count: 189, name: "The Brothers' War Retro Artifacts" },
    { code: "pbro", count: 171, name: "The Brothers' War Promos" },
    { code: "bro", count: 399, name: "The Brothers' War" },
    { code: "gn3", count: 135, name: "Game Night: Free-for-All" },
    { code: "unf", count: 639, name: "Unfinity" },
    { code: "40k", count: 618, name: "Warhammer 40,000 Commander" },
    { code: "pdmu", count: 160, name: "Dominaria United Promos" },
    { code: "dmc", count: 240, name: "Dominaria United Commander" },
    { code: "dmu", count: 453, name: "Dominaria United" },
    { code: "2x2", count: 579, name: "Double Masters 2022" },
    { code: "hbg", count: 436, name: "Alchemy Horizons: Baldur's Gate" },
    { code: "pclb", count: 104, name: "Battle for Baldur's Gate Promos" },
    {
      code: "clb",
      count: 936,
      name: "Commander Legends: Battle for Baldur's Gate",
    },
    { code: "snc", count: 513, name: "Streets of New Capenna" },
    { code: "ncc", count: 447, name: "New Capenna Commander" },
    { code: "psnc", count: 160, name: "Streets of New Capenna Promos" },
    { code: "pneo", count: 146, name: "Kamigawa: Neon Dynasty Promos" },
    { code: "neo", count: 531, name: "Kamigawa: Neon Dynasty" },
    { code: "nec", count: 179, name: "Neon Dynasty Commander" },
    { code: "dbl", count: 535, name: "Innistrad: Double Feature" },
    { code: "pvow", count: 112, name: "Innistrad: Crimson Vow Promos" },
    { code: "vow", count: 423, name: "Innistrad: Crimson Vow" },
    { code: "voc", count: 188, name: "Crimson Vow Commander" },
    { code: "mic", count: 187, name: "Midnight Hunt Commander" },
    { code: "pmid", count: 152, name: "Innistrad: Midnight Hunt Promos" },
    { code: "mid", count: 400, name: "Innistrad: Midnight Hunt" },
    { code: "j21", count: 389, name: "Jumpstart: Historic Horizons" },
    { code: "cmb2", count: 121, name: "Mystery Booster Playtest Cards 2021" },
    {
      code: "pafr",
      count: 240,
      name: "Adventures in the Forgotten Realms Promos",
    },
    { code: "afc", count: 331, name: "Forgotten Realms Commander" },
    { code: "afr", count: 424, name: "Adventures in the Forgotten Realms" },
    { code: "amh2", count: 162, name: "Modern Horizons 2 Art Series" },
    { code: "mh2", count: 494, name: "Modern Horizons 2" },
    { code: "pstx", count: 164, name: "Strixhaven: School of Mages Promos" },
    { code: "c21", count: 409, name: "Commander 2021" },
    { code: "astx", count: 162, name: "Strixhaven Art Series" },
    { code: "sta", count: 126, name: "Strixhaven Mystical Archive" },
    { code: "stx", count: 393, name: "Strixhaven: School of Mages" },
    { code: "tsr", count: 411, name: "Time Spiral Remastered" },
    { code: "pkhm", count: 153, name: "Kaldheim Promos" },
    { code: "khm", count: 426, name: "Kaldheim" },
    { code: "khc", count: 119, name: "Kaldheim Commander" },
    { code: "cmr", count: 718, name: "Commander Legends" },
    { code: "klr", count: 302, name: "Kaladesh Remastered" },
    { code: "plst", count: 4809, name: "The List" },
    { code: "pznr", count: 152, name: "Zendikar Rising Promos" },
    { code: "znr", count: 408, name: "Zendikar Rising" },
    { code: "znc", count: 142, name: "Zendikar Rising Commander" },
    { code: "akr", count: 339, name: "Amonkhet Remastered" },
    { code: "anb", count: 120, name: "Arena Beginner Set" },
    { code: "2xm", count: 384, name: "Double Masters" },
    { code: "jmp", count: 497, name: "Jumpstart" },
    { code: "pm21", count: 136, name: "Core Set 2021 Promos" },
    { code: "m21", count: 397, name: "Core Set 2021" },
    { code: "piko", count: 136, name: "Ikoria: Lair of Behemoths Promos" },
    { code: "iko", count: 390, name: "Ikoria: Lair of Behemoths" },
    { code: "c20", count: 322, name: "Commander 2020" },
    { code: "pthb", count: 136, name: "Theros Beyond Death Promos" },
    { code: "thb", count: 358, name: "Theros Beyond Death" },
    { code: "sld", count: 1681, name: "Secret Lair Drop" },
    { code: "cmb1", count: 121, name: "Mystery Booster Playtest Cards 2019" },
    { code: "peld", count: 136, name: "Throne of Eldraine Promos" },
    { code: "eld", count: 399, name: "Throne of Eldraine" },
    { code: "c19", count: 302, name: "Commander 2019" },
    { code: "pm20", count: 143, name: "Core Set 2020 Promos" },
    { code: "m20", count: 345, name: "Core Set 2020" },
    { code: "mh1", count: 255, name: "Modern Horizons" },
    { code: "pwar", count: 175, name: "War of the Spark Promos" },
    { code: "war", count: 312, name: "War of the Spark" },
    { code: "gk2", count: 133, name: "RNA Guild Kit" },
    { code: "rna", count: 273, name: "Ravnica Allegiance" },
    { code: "uma", count: 254, name: "Ultimate Masters" },
    { code: "gk1", count: 127, name: "GRN Guild Kit" },
    { code: "grn", count: 273, name: "Guilds of Ravnica" },
    { code: "c18", count: 307, name: "Commander 2018" },
    { code: "m19", count: 314, name: "Core Set 2019" },
    { code: "cm2", count: 312, name: "Commander Anthology Volume II" },
    { code: "bbd", count: 256, name: "Battlebond" },
    { code: "pdom", count: 118, name: "Dominaria Promos" },
    { code: "dom", count: 280, name: "Dominaria" },
    { code: "a25", count: 249, name: "Masters 25" },
    { code: "rix", count: 205, name: "Rivals of Ixalan" },
    { code: "ust", count: 268, name: "Unstable" },
    { code: "ima", count: 249, name: "Iconic Masters" },
    { code: "pxln", count: 120, name: "Ixalan Promos" },
    { code: "xln", count: 289, name: "Ixalan" },
    { code: "c17", count: 309, name: "Commander 2017" },
    { code: "hou", count: 209, name: "Hour of Devastation" },
    { code: "e01", count: 106, name: "Archenemy: Nicol Bolas" },
    { code: "cma", count: 320, name: "Commander Anthology" },
    { code: "akh", count: 287, name: "Amonkhet" },
    { code: "mm3", count: 249, name: "Modern Masters 2017" },
    { code: "aer", count: 197, name: "Aether Revolt" },
    { code: "pca", count: 156, name: "Planechase Anthology" },
    { code: "pz2", count: 282, name: "Treasure Chest" },
    { code: "c16", count: 351, name: "Commander 2016" },
    { code: "kld", count: 278, name: "Kaladesh" },
    { code: "cn2", count: 222, name: "Conspiracy: Take the Crown" },
    { code: "emn", count: 208, name: "Eldritch Moon" },
    { code: "ema", count: 249, name: "Eternal Masters" },
    { code: "soi", count: 302, name: "Shadows over Innistrad" },
    { code: "ogw", count: 187, name: "Oath of the Gatewatch" },
    { code: "pz1", count: 149, name: "Legendary Cube Prize Pack" },
    { code: "c15", count: 342, name: "Commander 2015" },
    { code: "bfz", count: 299, name: "Battle for Zendikar" },
    { code: "ori", count: 288, name: "Magic Origins" },
    { code: "mm2", count: 249, name: "Modern Masters 2015" },
    { code: "tpr", count: 269, name: "Tempest Remastered" },
    { code: "dtk", count: 264, name: "Dragons of Tarkir" },
    { code: "frf", count: 191, name: "Fate Reforged" },
    { code: "c14", count: 337, name: "Commander 2014" },
    { code: "ktk", count: 293, name: "Khans of Tarkir" },
    { code: "m15", count: 284, name: "Magic 2015" },
    { code: "vma", count: 325, name: "Vintage Masters" },
    { code: "cns", count: 210, name: "Conspiracy" },
    { code: "jou", count: 165, name: "Journey into Nyx" },
    { code: "bng", count: 165, name: "Born of the Gods" },
    { code: "c13", count: 356, name: "Commander 2013" },
    { code: "ths", count: 249, name: "Theros" },
    { code: "m14", count: 249, name: "Magic 2014" },
    { code: "mma", count: 229, name: "Modern Masters" },
    { code: "dgm", count: 156, name: "Dragon's Maze" },
    { code: "gtc", count: 249, name: "Gatecrash" },
    { code: "rtr", count: 274, name: "Return to Ravnica" },
    { code: "m13", count: 249, name: "Magic 2013" },
    { code: "pc2", count: 156, name: "Planechase 2012" },
    { code: "avr", count: 244, name: "Avacyn Restored" },
    { code: "dka", count: 158, name: "Dark Ascension" },
    { code: "isd", count: 264, name: "Innistrad" },
    { code: "m12", count: 249, name: "Magic 2012" },
    { code: "cmd", count: 318, name: "Commander 2011" },
    { code: "nph", count: 175, name: "New Phyrexia" },
    { code: "mbs", count: 155, name: "Mirrodin Besieged" },
    { code: "me4", count: 269, name: "Masters Edition IV" },
    { code: "ps11", count: 224, name: "Salvat 2011" },
    { code: "td0", count: 197, name: "Magic Online Theme Decks" },
    { code: "som", count: 249, name: "Scars of Mirrodin" },
    { code: "m11", count: 249, name: "Magic 2011" },
    { code: "arc", count: 150, name: "Archenemy" },
    { code: "dpa", count: 113, name: "Duels of the Planeswalkers" },
    { code: "roe", count: 248, name: "Rise of the Eldrazi" },
    { code: "wwk", count: 145, name: "Worldwake" },
    { code: "zen", count: 269, name: "Zendikar" },
    { code: "me3", count: 230, name: "Masters Edition III" },
    { code: "hop", count: 169, name: "Planechase" },
    { code: "m10", count: 249, name: "Magic 2010" },
    { code: "arb", count: 145, name: "Alara Reborn" },
    { code: "con", count: 145, name: "Conflux" },
    { code: "ala", count: 250, name: "Shards of Alara" },
    { code: "me2", count: 245, name: "Masters Edition II" },
    { code: "eve", count: 180, name: "Eventide" },
    { code: "shm", count: 302, name: "Shadowmoor" },
    { code: "mor", count: 150, name: "Morningtide" },
    { code: "lrw", count: 301, name: "Lorwyn" },
    { code: "me1", count: 195, name: "Masters Edition" },
    { code: "10e", count: 510, name: "Tenth Edition" },
    { code: "fut", count: 180, name: "Future Sight" },
    { code: "plc", count: 165, name: "Planar Chaos" },
    { code: "tsp", count: 301, name: "Time Spiral" },
    { code: "tsb", count: 121, name: "Time Spiral Timeshifted" },
    { code: "csp", count: 155, name: "Coldsnap" },
    { code: "dis", count: 180, name: "Dissension" },
    { code: "gpt", count: 167, name: "Guildpact" },
    { code: "rav", count: 306, name: "Ravnica: City of Guilds" },
    { code: "psal", count: 720, name: "Salvat 2005" },
    { code: "9ed", count: 709, name: "Ninth Edition" },
    { code: "sok", count: 165, name: "Saviors of Kamigawa" },
    { code: "bok", count: 165, name: "Betrayers of Kamigawa" },
    { code: "unh", count: 168, name: "Unhinged" },
    { code: "chk", count: 307, name: "Champions of Kamigawa" },
    { code: "wc04", count: 103, name: "World Championship Decks 2004" },
    { code: "5dn", count: 165, name: "Fifth Dawn" },
    { code: "dst", count: 165, name: "Darksteel" },
    { code: "mrd", count: 306, name: "Mirrodin" },
    { code: "wc03", count: 142, name: "World Championship Decks 2003" },
    { code: "8ed", count: 710, name: "Eighth Edition" },
    { code: "scg", count: 143, name: "Scourge" },
    { code: "lgn", count: 145, name: "Legions" },
    { code: "ons", count: 351, name: "Onslaught" },
    { code: "wc02", count: 153, name: "World Championship Decks 2002" },
    { code: "prm", count: 3105, name: "Magic Online Promos" },
    { code: "jud", count: 143, name: "Judgment" },
    { code: "tor", count: 143, name: "Torment" },
    { code: "ody", count: 353, name: "Odyssey" },
    { code: "wc01", count: 138, name: "World Championship Decks 2001" },
    { code: "apc", count: 143, name: "Apocalypse" },
    { code: "7ed", count: 708, name: "Seventh Edition" },
    { code: "pls", count: 146, name: "Planeshift" },
    { code: "inv", count: 353, name: "Invasion" },
    { code: "wc00", count: 117, name: "World Championship Decks 2000" },
    { code: "pcy", count: 144, name: "Prophecy" },
    { code: "nem", count: 143, name: "Nemesis" },
    { code: "brb", count: 136, name: "Battle Royale Box Set" },
    { code: "mmq", count: 350, name: "Mercadian Masques" },
    { code: "wc99", count: 111, name: "World Championship Decks 1999" },
    { code: "s99", count: 173, name: "Starter 1999" },
    { code: "uds", count: 143, name: "Urza's Destiny" },
    { code: "ptk", count: 180, name: "Portal Three Kingdoms" },
    { code: "6ed", count: 351, name: "Classic Sixth Edition" },
    { code: "ulg", count: 143, name: "Urza's Legacy" },
    { code: "usg", count: 356, name: "Urza's Saga" },
    { code: "wc98", count: 117, name: "World Championship Decks 1998" },
    { code: "p02", count: 165, name: "Portal Second Age" },
    { code: "exo", count: 143, name: "Exodus" },
    { code: "sth", count: 143, name: "Stronghold" },
    { code: "tmp", count: 350, name: "Tempest" },
    { code: "wc97", count: 131, name: "World Championship Decks 1997" },
    { code: "wth", count: 167, name: "Weatherlight" },
    { code: "por", count: 257, name: "Portal" },
    { code: "5ed", count: 460, name: "Fifth Edition" },
    { code: "vis", count: 167, name: "Visions" },
    { code: "mir", count: 353, name: "Mirage" },
    { code: "all", count: 199, name: "Alliances" },
    { code: "ptc", count: 308, name: "Pro Tour Collector Set" },
    { code: "hml", count: 140, name: "Homelands" },
    { code: "ren", count: 122, name: "Renaissance" },
    { code: "bchr", count: 125, name: "Chronicles Foreign Black Border" },
    { code: "chr", count: 125, name: "Chronicles" },
    { code: "ice", count: 383, name: "Ice Age" },
    { code: "4bb", count: 378, name: "Fourth Edition Foreign Black Border" },
    { code: "4ed", count: 379, name: "Fourth Edition" },
    { code: "fem", count: 187, name: "Fallen Empires" },
    { code: "drk", count: 122, name: "The Dark" },
    { code: "sum", count: 306, name: "Summer Magic / Edgar" },
    { code: "leg", count: 310, name: "Legends" },
    { code: "fbb", count: 307, name: "Foreign Black Border" },
    { code: "3ed", count: 306, name: "Revised Edition" },
    { code: "atq", count: 102, name: "Antiquities" },
    { code: "cei", count: 302, name: "Intl. Collectors' Edition" },
    { code: "ced", count: 302, name: "Collectors' Edition" },
    { code: "2ed", count: 302, name: "Unlimited Edition" },
    { code: "leb", count: 302, name: "Limited Edition Beta" },
    { code: "lea", count: 295, name: "Limited Edition Alpha" },
  ],
};
